<a href="https://colab.research.google.com/github/ThanhQuynh0202/VoNgocThanhQuynh_20104053/blob/main/11_10_22.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
from sklearn.linear_model import Perceptron
x = [[0,0], [1,0], [0,1], [1,1]]
y = [0,1,1,1]
model = Perceptron()
model.fit(x,y)
print('Do chinh xac', model.score(x,y))
x_test= [[0.5, 0], [0.9, -0,2], [1, -0.5], [0.2,0.7]]
y_test = model.predict(x_test)
print(y_test)

In [ ]:
import numpy as np
from sklearn.linear_model import Perceptron
x = [[-0.5,-0.5], [-0.5,0.5], [0.3,-0.5], [-0.1,1]]
y = [1,1,0,0]
model = Perceptron()
model.fit(x,y)
print('Do chinh xac', model.score(x,y))
x_test= [[0.5, 0], [0.9, -0,2], [1, -0.5], [0.2,0.7]]
y_test = model.predict(x_test)
print(y_test)

In [ ]:
import numpy as np
from sklearn.linear_model import Perceptron
x=[[0,0],[1,0],[0,1],[1,1]]
y=[0,1,1,1]
model=Perceptron()
model.fit(x,y)
print('do chinh xac',model.score(x,y))
x_test=[[0.5,0],[0.9,-0.2],[1,-0.5],[0.2,0.7]]
y_test=model.predict(x_test)
print(y_test)

do chinh xac 1.0
[0 1 0 1]


In [ ]:
import numpy as np
from sklearn.linear_model import Perceptron
x=[[-0.5,-0.5], [-0.5,0.5], [0.3,-0.5], [-0.1,1]]
y=[1,1,0,0]
model=Perceptron()
model.fit(x,y)
print('do chinh xac',model.score(x,y))
x_test=[[0.5,0],[0.9,-0.2],[1,-0.5],[0.2,0.7]]
y_test=model.predict(x_test)
print(y_test)

do chinh xac 1.0
[0 0 0 0]


In [ ]:
import pandas as pd
import numpy as np
from sklearn.linear_model import Perceptron
from sklearn.model_selection import train_test_split

url = '/content/crabs.csv'
data = pd.read_csv(url)  
X = data.drop(["speies", "sex"], axis = True)
Y = data["sex"].replace(['M', 'F'], [0,1])
X_train, X_test, Y_train, Y_test = train_test_split(X,Y,test_size = 0.3) 
model = Perceptron()
model.fit(X_train, Y_train)
score_train = model.score(X_train, Y_train)
print(f'DO chinh xac: {score_train}')
Y_het = model.predict(X_test)
cal = pd.data(np.c_[Y_test, Y_het], columns = ['tested y', 'predicted y'])
print(cal)

DO chinh xac: 0.9071428571428571


AttributeError: ignored

In [ ]:
import numpy as np
from sklearn.linear_model import Perceptron
from sklearn.model_selection import train_test_split
import pandas as pd

url = "/content/crabs.csv"
data = pd.read_csv(url)
x = data.drop(data.columns[[0,1,2]], axis=1)
y = data["sex"].replace(["M","F"],[1,0])

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.3)

model = Perceptron()
model.fit(x_train, y_train)
print("Độ chính xác: ", model.score(x_train,y_train))

x_input = [[10.8,9,23,26.5,9.8], [10.8,9.5,22.5,26.3,9.1]]
y_pred = model.predict(x_input)

print(y_pred)

Độ chính xác:  0.8
[1 1]


/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but Perceptron was fitted with feature names
  "X does not have valid feature names, but"


In [ ]:
import pandas as pd
import numpy as np
from sklearn.linear_model import Perceptron
from sklearn.model_selection import train_test_split

crab = 'crabs.csv'
crab_data = pd.read_csv(crab)
data = (crab_data.drop('speies',axis = 1)).drop('index',axis = 1)
data.replace(to_replace ='M',value = 1)
data.replace(to_replace ='F',value = 0)

X = data.drop(["speies", "sex"], axis = True)
Y = data["sex"].replace(['M', 'F'], [0,1])

model = Perceptron()
model.fit(x,y)
print('Do chinh xac',model.score(x,y))
x_test = [[6,9.8,8.9,20.4,23.9,8.8]]
y_test = model.predict(x_test)
print('sex: ',y_test)

KeyError: ignored

In [ ]:
from sklearn.datasets import load_iris



In [ ]:
import numpy as np
from sklearn.linear_model import Perceptron
from sklearn.model_selection import train_test_split 
from sklearn.datasets import load_iris
import pandas as pd
url = '/content/iris.csv'
data = pd.read_csv(url)
data = data[:100]
x= data.drop(['variety'],axis = True)
y= data['variety'].replace(['Setosa','Versicolor','Virginica'],[1,0,0])
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.3)
model = Perceptron()
model.fit(x_train,y_train)
print('Độ chính xác: ', model.score(x_train,y_train))
x_input = [[4.9,3,1.4,0.2],[4.6,3.1,1.5,0.2],[7.7,2.6,6.9,2.3]]
y_pred = model.predict(x_input)
print(y_pred)


Độ chính xác:  1.0
[1 1 0]


/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but Perceptron was fitted with feature names
  "X does not have valid feature names, but"
